services:
  postgres-keycloak:
    image: postgres:15
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" # Puerto diferente para no colisionar con otras DB
    networks:
      - ecommerce-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak-server
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev # Modo desarrollo para facilitar la configuración inicial
    ports:
      - "8080:8080"
    depends_on:
      - postgres-keycloak
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge