server:
  port: 8084

spring:
  application:
    name: order-service

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update # Solo para desarrollo
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc: # Configuracion para el guardado de las Reservas
          batch_size: 50
          order_inserts: true
          order_updates: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # Permite descargar las llaves públicas de Keycloak
          issuer-uri: http://localhost:8080/realms/ecommerce-realm

      # Configuración como Cliente (Para enviar peticiones a otros servicios)
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/ecommerce-realm
        registration:
          order-service-client:
            provider: keycloak
            client-id: order-service
            client-secret: ${KEYCLOAK_ORDER_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            # BLINDAJE: Fuerza el envío de credenciales en la cabecera (Estándar Keycloak)
            client-authentication-method: client_secret_post

feign:
  circuitbreaker:
    enabled: true # Integración nativa de Feign con Resilience4j

# Configuracion Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      catalogService: # Nombre de la instancia
        registerHealthIndicator: true
        slidingWindowSize: 10 # Evalua las ultimas 10 peticiones
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
      inventoryService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    instances:
      catalogService:
        timeoutDuration: 2s # Fast-Fail: Si tarda mas de 2 segundos, lo cuenta como fallo
      inventoryService:
        timeoutDuration: 6s # Dar margen a la escritura de las Reservas

# Cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    # Sobreescritura del Identificador de Instancia (Elimina la dependencia de InetUtils)
    instance-id: localhost:${spring.application.name}:${server.port}